version: "3.8"
networks:
  default:
    external: true
    name: 2_default
services:
  web:
    image: shockwallet/api:latest
    command: -c -h 0.0.0.0 -l polar-n2-alice:10009 -m /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon -d /root/.lnd/tls.cert
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 9835:9835
    volumes:
      - C:\Users\boufn\.polar\networks\2\volumes\lnd\alice:/root/.lnd
    environment:
      TRUSTED_KEYS: 'false'