version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: lightning-pub
      APP_PORT: 1776
      
  server:
    image: ghcr.io/shocknet/lightning.pub:umbrel-works
    volumes:
      - "${APP_DATA_DIR}/data:/data"
      - "${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro"
    environment:
      LN_BACKEND_TYPE: "LND"
      LND_ADDRESS: $APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_GRPC_PORT
      LND_CERT_PATH: "/lnd/tls.cert"
      LND_MACAROON_PATH: "/lnd/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/admin.macaroon"
      DATABASE_FILE: "/data/db.sqlite"
      METRICS_DATABASE_FILE: "/data/metrics.sqlite"
      PORT: 1776
    restart: on-failure
    stop_grace_period: 1m
