name: Update Wizard

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Bump Wizard Version'
        required: false
        default: 'yes'

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['shocknet/Wizard']
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          ref: ${{ github.ref }}

      - name: âš™ï¸ Install Dependencies
        run: yarn install

      - name: ğŸ“ Test GunDB
        run: yarn test:gun

      - name: ğŸ“¯ Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: api-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
